package service

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"

	"github.com/nanashiwang/meta-pulse/internal/domain/ledger"
	"github.com/nanashiwang/meta-pulse/internal/ports"
)

// AdminAdjustmentCommand describes a manually reviewed correction. RequestID
// is the business idempotency key and must be generated by the admin API, not
// by a retrying browser.
type AdminAdjustmentCommand struct {
	ActorType    string
	ActorID      string
	UserID       uint64
	PeriodID     uint64
	AssetType    ledger.AssetType
	Amount       int64
	Reason       string
	RequestID    string
	MetadataJSON []byte
}

type AdminAdjustmentResult struct {
	Entry ledger.Entry `json:"entry"`
}

type AdminAdjustmentService struct {
	unit ports.UnitOfWork
	now  func() time.Time
}

func NewAdminAdjustmentService(unit ports.UnitOfWork, now func() time.Time) (*AdminAdjustmentService, error) {
	if unit == nil {
		return nil, errors.New("admin adjustment unit of work is nil")
	}
	if now == nil {
		now = time.Now
	}
	return &AdminAdjustmentService{unit: unit, now: now}, nil
}

func (s *AdminAdjustmentService) Apply(ctx context.Context, command AdminAdjustmentCommand) (AdminAdjustmentResult, error) {
	if err := validateAdjustmentCommand(command); err != nil {
		return AdminAdjustmentResult{}, err
	}
	operation := adjustmentOperation(command.AssetType)
	payloadHash := adjustmentPayloadHash(command, operation)
	var result AdminAdjustmentResult
	err := s.unit.Do(ctx, func(repos ports.Repositories) error {
		if repos.Ledger == nil || repos.Account == nil || repos.Idempotency == nil || repos.Audit == nil {
			return errors.New("admin adjustment repositories are not initialized")
		}
		idempotency, err := repos.Idempotency.GetOrCreateForUpdate(ctx, "admin_adjustment", command.RequestID, payloadHash)
		if err != nil {
			return err
		}
		if idempotency.PayloadHash != payloadHash {
			return fmt.Errorf("%w: admin adjustment request=%s", ledger.ErrIdempotencyConflict, command.RequestID)
		}
		if len(idempotency.ResponseJSON) > 0 {
			if err := json.Unmarshal(idempotency.ResponseJSON, &result); err != nil {
				return fmt.Errorf("decode idempotent adjustment response: %w", err)
			}
			return nil
		}

		// Ticket balances cannot become negative. The account is locked here and
		// locked again by appendEntry in the same transaction.
		if command.AssetType == ledger.AssetTicket && command.Amount < 0 {
			if command.Amount == math.MinInt64 {
				return fmt.Errorf("%w: ticket adjustment amount is out of range", ledger.ErrInvalidEntry)
			}
			account, err := repos.Account.GetOrCreateForUpdate(ctx, command.UserID, command.PeriodID, command.AssetType)
			if err != nil {
				return err
			}
			if account.Balance < -command.Amount {
				return fmt.Errorf("%w: ticket adjustment would make balance negative", ErrInsufficientTickets)
			}
		}
		entry, err := appendEntry(ctx, repos, ledger.Entry{
			UserID: command.UserID, PeriodID: command.PeriodID, AssetType: command.AssetType,
			Operation: operation, Amount: command.Amount, SourceType: "admin_adjustment",
			SourceRef: command.RequestID, IdempotencyKey: "admin-adjustment:" + command.RequestID,
			PayloadHash: payloadHash, Reason: command.Reason, MetadataJSON: append([]byte(nil), command.MetadataJSON...), CreatedAt: s.now(),
		})
		if err != nil {
			return err
		}
		before := entry.BalanceAfter - entry.Amount
		beforeJSON, err := json.Marshal(struct {
			Balance int64 `json:"balance"`
		}{Balance: before})
		if err != nil {
			return err
		}
		afterJSON, err := json.Marshal(struct {
			Balance int64        `json:"balance"`
			Entry   ledger.Entry `json:"entry"`
		}{Balance: entry.BalanceAfter, Entry: entry})
		if err != nil {
			return err
		}
		if err := repos.Audit.Append(ctx, ports.AuditLog{
			ActorType: command.ActorType, ActorID: command.ActorID, Action: "ledger_adjustment",
			ResourceType: "ledger_entry", ResourceID: command.RequestID, Reason: command.Reason,
			BeforeJSON: beforeJSON, AfterJSON: afterJSON, RequestID: command.RequestID, CreatedAt: s.now(),
		}); err != nil {
			return err
		}
		result = AdminAdjustmentResult{Entry: entry}
		response, err := json.Marshal(result)
		if err != nil {
			return err
		}
		status := 201
		idempotency.ResponseStatus = &status
		idempotency.ResponseJSON = response
		idempotency.ResourceType = "ledger_entry"
		idempotency.ResourceID = fmt.Sprintf("%d", entry.ID)
		return repos.Idempotency.Save(ctx, idempotency)
	})
	if err != nil {
		return AdminAdjustmentResult{}, err
	}
	return result, nil
}

func validateAdjustmentCommand(command AdminAdjustmentCommand) error {
	if strings.TrimSpace(command.ActorType) == "" || strings.TrimSpace(command.ActorID) == "" {
		return errors.New("adjustment actor is required")
	}
	if command.UserID == 0 || command.PeriodID == 0 {
		return errors.New("adjustment user and period are required")
	}
	if command.AssetType != ledger.AssetContribution && command.AssetType != ledger.AssetTicket {
		return fmt.Errorf("%w: unsupported adjustment asset", ledger.ErrInvalidEntry)
	}
	if command.Amount == 0 {
		return fmt.Errorf("%w: adjustment amount cannot be zero", ledger.ErrInvalidEntry)
	}
	if strings.TrimSpace(command.Reason) == "" {
		return errors.New("adjustment reason is required")
	}
	if strings.TrimSpace(command.RequestID) == "" {
		return errors.New("adjustment request id is required")
	}
	if len(command.RequestID) > 128 {
		return errors.New("adjustment request id is too long")
	}
	return nil
}

func adjustmentOperation(asset ledger.AssetType) ledger.Operation {
	if asset == ledger.AssetTicket {
		return ledger.OperationTicketAdjustment
	}
	return ledger.OperationContributionAdjustment
}

func adjustmentPayloadHash(command AdminAdjustmentCommand, operation ledger.Operation) string {
	payload, _ := json.Marshal(struct {
		ActorType    string           `json:"actor_type"`
		ActorID      string           `json:"actor_id"`
		UserID       uint64           `json:"user_id"`
		PeriodID     uint64           `json:"period_id"`
		AssetType    ledger.AssetType `json:"asset_type"`
		Operation    ledger.Operation `json:"operation"`
		Amount       int64            `json:"amount"`
		Reason       string           `json:"reason"`
		RequestID    string           `json:"request_id"`
		MetadataJSON []byte           `json:"metadata_json"`
	}{command.ActorType, command.ActorID, command.UserID, command.PeriodID, command.AssetType, operation, command.Amount, command.Reason, command.RequestID, command.MetadataJSON})
	digest := sha256.Sum256(payload)
	return hex.EncodeToString(digest[:])
}
