#!/usr/bin/env python3
"""One route inventory for the gateway, METAR router and Answer bridge."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def generate(check=False):
    manifest = json.loads((ROOT / 'metar-frontend/shared/routes.json').read_text())
    pages = manifest['pages']
    prefixes = manifest['detailPrefixes']
    if len(pages) != len(set(pages)) or any(not re.fullmatch(r'[a-z]+(?:/[a-z]+)*', p) for p in pages + prefixes):
        raise ValueError('invalid or duplicate route')
    pattern = '^/(?:' + '|'.join(pages) + '|(?:' + '|'.join(prefixes) + ')/[^/]+)/?$'
    core = '''  const pattern = new RegExp(PATTERN);
  const aliases = Object.freeze(ALIASES);
  function owns(path) { return path === '/' || pattern.test(path); }
  function target(value, origin) {
    if (typeof value !== 'string' || /[\\\\\\u0000-\\u0020]/.test(value)) return null;
    try {
      const url = new URL(value, origin);
      if (url.origin !== origin || url.username || url.password || !owns(url.pathname)) return null;
      // Never send encoded separators or dot segments to a different handler
      // after nginx decodes the path. Query and fragment remain untouched.
      const decoded = decodeURIComponent(url.pathname);
      if (/[\\\\\\u0000-\\u001f]/.test(decoded) || decoded.split('/').some(p => p === '.' || p === '..') || decoded.split('/').length !== url.pathname.split('/').length) return null;
      return (url.pathname === '/' ? '/latest' : url.pathname) + url.search + url.hash;
    } catch (_) { return null; }
  }
'''.replace('PATTERN', json.dumps(pattern)).replace('ALIASES', json.dumps(manifest['legacyAliases']))
    banner = '// Generated by metar-frontend/shared/generate-routes.py; edit shared/routes.json.\n'
    browser = banner + "(function(root) {\n" + core + "  const policy = { owns, target, aliases };\n  if (typeof module === 'object' && module.exports) module.exports = policy;\n  else root.MetarRoutes = policy;\n})(typeof window === 'undefined' ? globalThis : window);\n"
    plugin = banner + core + '\nexport { owns, target, aliases };\n'
    nginx_path = ROOT / 'deploy/nginx/meta-pulse.conf'
    nginx = nginx_path.read_text()
    nginx, count = re.subn(r'    location ~ \^/\(\?:latest[^\n]+ \{', lambda _: '    location ~ ' + pattern + ' {', nginx)
    if count != 1:
        raise ValueError('expected one METAR gateway route block')
    outputs = {
        ROOT / 'metar-frontend/production/src/route-policy.js': browser,
        ROOT / 'services/forum-plugin/user-center-pulse/route-policy.js': plugin,
        nginx_path: nginx,
    }
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'{path.relative_to(ROOT)} is stale; run python3 metar-frontend/shared/generate-routes.py')
        else:
            path.write_text(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
