#!/usr/bin/env python3
"""Package shared browser code for Answer's vendored plugin and the static shell."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHARED = ROOT / 'metar-frontend/shared'


def generate(check=False):
    banner = '// Generated by metar-frontend/shared/generate-theme.py.\n'
    core = (SHARED / 'theme-core.js').read_text()
    exports = 'THEME_KEY, validTheme, createThemeController, installTheme'
    browser = banner + '(function(root) {\n' + core + '\nconst api = {' + exports + '};\n' + "if (typeof module === 'object' && module.exports) module.exports = api;\nelse { root.MetarTheme = api; api.installTheme(root); }\n})(typeof window === 'undefined' ? globalThis : window);\n"
    outputs = {
        ROOT / 'metar-frontend/production/src/theme.js': browser,
        ROOT / 'services/forum-plugin/user-center-pulse/shared-theme.js': banner + core + '\nexport { ' + exports + ' };\n',
        ROOT / 'services/forum-plugin/user-center-pulse/theme-tokens.css': (SHARED / 'theme-tokens.css').read_text(),
    }
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'{path.relative_to(ROOT)} is stale; run python3 metar-frontend/shared/generate-theme.py')
        else:
            path.write_text(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
