// Generated by metar-frontend/shared/generate-routes.py; edit shared/routes.json.
  const pattern = new RegExp("^/(?:latest|discover|topics|knowledge|search|me|me/bookmarks|me/notifications|settings/binding|pulse|admin/pulse|publish|login|register|forgot|support|status|guidelines|(?:question|topic)/[^/]+)/?$");
  const aliases = Object.freeze({"/discover": "/latest", "/questions": "/latest", "/bookmarks": "/me/bookmarks", "/notifications": "/me/notifications"});
  function owns(path) { return path === '/' || pattern.test(path); }
  function target(value, origin) {
    if (typeof value !== 'string' || /[\\\u0000-\u0020]/.test(value)) return null;
    try {
      const url = new URL(value, origin);
      if (url.origin !== origin || url.username || url.password || !owns(url.pathname)) return null;
      // Never send encoded separators or dot segments to a different handler
      // after nginx decodes the path. Query and fragment remain untouched.
      const decoded = decodeURIComponent(url.pathname);
      if (/[\\\u0000-\u001f]/.test(decoded) || decoded.split('/').some(p => p === '.' || p === '..') || decoded.split('/').length !== url.pathname.split('/').length) return null;
      return (url.pathname === '/' ? '/latest' : url.pathname) + url.search + url.hash;
    } catch (_) { return null; }
  }

export { owns, target, aliases };
