// Generated by metar-frontend/shared/generate-theme.py.
// Browser-local presentation only. Never writes an Answer profile or session.
const THEME_KEY = '_metar_theme';
const validTheme = (value) => value === 'dark' || value === 'light' ? value : null;

function createThemeController({ storage, system, apply }) {
  let preferred = null;
  try { preferred = validTheme(storage?.getItem(THEME_KEY)); } catch (_) { /* private browsing */ }
  const listeners = new Set();
  let notified;
  const current = () => preferred || (system.matches ? 'dark' : 'light');
  function sync() {
    const theme = current();
    apply(theme);
    if (notified !== theme) {
      notified = theme;
      listeners.forEach((listener) => listener(theme));
    }
  }
  const systemChanged = () => { if (!preferred) sync(); };
  system.addEventListener?.('change', systemChanged);
  sync();
  return {
    current,
    sync,
    select(value) {
      if (!validTheme(value)) return false;
      preferred = value;
      try { storage?.setItem(THEME_KEY, value); } catch (_) { /* retain in memory */ }
      sync();
      return true;
    },
    fromStorage(value) { preferred = validTheme(value); sync(); },
    subscribe(listener) { listeners.add(listener); listener(current()); return () => listeners.delete(listener); },
    dispose() { system.removeEventListener?.('change', systemChanged); listeners.clear(); },
  };
}

function installTheme(host = window, { native = false } = {}) {
  if (host.__metarTheme) return host.__metarTheme;
  const root = host.document.documentElement;
  let storage;
  try { storage = host.localStorage; } catch (_) { /* preference remains usable */ }
  const controller = createThemeController({
    storage,
    system: host.matchMedia('(prefers-color-scheme: dark)'),
    apply(theme) {
      if (root.getAttribute('data-theme') !== theme) root.setAttribute('data-theme', theme);
      if (native && root.getAttribute('data-bs-theme') !== theme) root.setAttribute('data-bs-theme', theme);
    },
  });
  host.addEventListener('storage', (event) => {
    if (event.key === THEME_KEY || event.key === null) controller.fromStorage(event.newValue);
  });
  if (native) {
    // Answer also applies system/site defaults after its async bootstrap.
    // Restore the effective browser choice without changing its server settings.
    let pending = false;
    new host.MutationObserver(() => {
      if (pending || root.getAttribute('data-bs-theme') === controller.current()) return;
      pending = true;
      host.requestAnimationFrame(() => { pending = false; controller.sync(); });
    }).observe(root, { attributes: true, attributeFilter: ['data-bs-theme'] });
  }
  host.__metarTheme = controller;
  return controller;
}

export { THEME_KEY, validTheme, createThemeController, installTheme };
